// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personal_Blog.Services;

#nullable disable

namespace Personal_Blog.Migrations
{
    [DbContext(typeof(ArticleContext))]
    [Migration("20250701171612_FixStaticSeedData")]
    partial class FixStaticSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Personal_Blog.Models.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            content = "Artificial Intelligence (AI) has become an integral part of our daily lives. \r\nFrom personalized recommendations on streaming platforms to voice assistants in our homes, \r\nAI is transforming the way we live, work, and interact with technology.\r\n\r\nThe healthcare sector is leveraging AI to improve diagnostics and treatment planning, \r\nwhile industries like finance and retail are using it to predict trends and optimize operations.\r\n\r\nAs the technology continues to evolve, it is crucial to ensure responsible and ethical use of AI \r\nto maximize benefits while minimizing risks.",
                            date = new DateTime(2025, 7, 1, 19, 16, 11, 40, DateTimeKind.Local).AddTicks(669),
                            heading = "The Rise of AI in Everyday Life"
                        });
                });

            modelBuilder.Entity("Personal_Blog.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            password = "AdminPassword123",
                            username = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
